TESTING = True

SQLALCHEMY_DATABASE_URI_BASE = "postgresql://postgres:root@localhost/"
SQLALCHEMY_DATABASE_NAME = "exeris_test"
SQLALCHEMY_DATABASE_URI = SQLALCHEMY_DATABASE_URI_BASE + SQLALCHEMY_DATABASE_NAME
SQLALCHEMY_ECHO = False
SQLALCHEMY_RECORD_QUERIES = True
