version: '3.7'
services:
    backend:
        build:
          context: .
          dockerfile: Dockerfile.dev
        ports:
          - "5000:5000"
        volumes:
          - .:/app
        depends_on:
         - postgres
         - redis
        environment:
          - EXERIS_CONFIG_PATH=config/dev_config.py
    postgres:
        image: postgis/postgis:13-3.0-alpine
        environment:
          - POSTGRES_PASSWORD=root
    redis:
        image: redis:6.0.9-alpine
networks:
    default:
        name: exeris_dev
