FROM python:3.9.0-buster

WORKDIR /app/

COPY requirements.txt /app/

RUN apt-get update \
    && apt-get install -y libgeos-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install -r requirements.txt

COPY . /app/

CMD ["python", "run.py"]
